### PR TITLE
Dev Security Page

### PR DESCRIPTION
**Pull request by codingknite**
- Current Commit Covers the Mobile Version of page. Will be pushing the desktop version in a bit

### CODE REVIEW

**Comment by maximousblk** [comment]
#### 📝 Changed routes:


| [**/**](https://arconnect-web-new-cqoz4jxpc-th8ta.vercel.app/) | [**/security**](https://arconnect-web-new-cqoz4jxpc-th8ta.vercel.app/security) |
|:-:|:-:|
|<a href="https://arconnect-web-new-cqoz4jxpc-th8ta.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/51Tp6HS8JXDtEYNU8ibAE7RgZc5PuiGDFuhi8H857Ri_3kd-SEIs__KUasM9qhVkbQrffMnyBlVjgpDVj1ofHQ.png">(view full size)</a> |<a href="https://arconnect-web-new-cqoz4jxpc-th8ta.vercel.app/security">Screenshot of /security</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/LdOfqXcpUMT6mP_AisTi8FYfiZmfifbhJ8mFuEiB-_Q0vSn7kdgk4T5ml-UTBiEPH7S4nAR-FyWvuRpSmpx3jw.png">(view full size)</a> |







Commit 0aaf688f931889dab2b8e7c3c50b37d0ffdd790a (https://arconnect-web-new-cqoz4jxpc-th8ta.vercel.app).

**Comment by t8** [comment]
There are some updates that need to be made to site content. Will be pushing some commits shortly, but will wait until merge conflicts are resolved.

**Comment by codingknite** [comment]
Hey @t8 the merge conflicts have been resolved. Ready for the new content

**Review by t8 — CHANGES_REQUESTED** [review]
Amazing work here @codingknite! I just pushed some quick content updates to spare all the granular commits you had to make last time I reviewed the first PR.

**Just a few suggestions before we merge this:**
The "Learn More" button should redirect to https://docs.th8ta.org/arconnect/permissions when clicked. It also changes in height when hovered, shifting the text above. Let's try to remove the text shifting.
image

The bottom "Chat With Us" button changes the text color when hovered:
Before hover:
image
During hover:
image

Once these updates are made, we should be good to go!

**Comment by t8** [comment]
@codingknite it seems that the button animations have been removed and the text color bug still persists 😅 

Could we fix that?

**Review by t8 — APPROVED** [review]
LGTM!

Feel free to merge as soon as that merge conflict is resolved :)

**Pull request merged**
